// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package filesimportmodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the FilesImportModule module

	public static java.lang.String getFilesImportLogNodeName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("FilesImportModule.FilesImportLogNodeName");
	}
}