// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package filesimportmodule.proxies;

public enum ArchiveType
{
	autodetect(new java.lang.String[][] { new java.lang.String[] { "en_US", "<autodetect>" } }),
	ZIP(new java.lang.String[][] { new java.lang.String[] { "en_US", "zip" } }),
	SEVEN_Z(new java.lang.String[][] { new java.lang.String[] { "en_US", "7zip" } }),
	TAR(new java.lang.String[][] { new java.lang.String[] { "en_US", "tar" } }),
	tar_gz(new java.lang.String[][] { new java.lang.String[] { "en_US", "tar.gz" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ArchiveType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
